{
  "instruction": "This code generates connector models using CadQuery. To run the script, ensure that freecad (v1.5 and v1.6 have been tested) and cadquery FreeCAD plugin (v0.3.0 and v0.2.0 have been tested) are installed. To generate VRML/STEP files, use the export_conn_jst_xh script of the parent directory. The script generates models for the 4UCON 17809 series connectors. To generate a specific part, set the part_to_build variable to the desired part key. The generate_part function generates the pins, body, and contacts for the specified part key. The pins, body, and contacts can be displayed using the show function.",
  "buggy_code": "__title__ = 'model description for 4UCON 17809 series connectors'\n__author__ = 'hackscribble'\n__Comment__ = 'model description for 4UCON 17809 series connectors using cadquery'\n___ver___ = '0.3 18/06/2020'\nimport cadquery as cq\nfrom Helpers import show\nfrom collections import namedtuple\nimport FreeCAD\nfrom conn_4ucon_17809_params import *\nfrom ribbon import Ribbon\n\ndef generate_straight_pin(params, pin_1_side):\n    foot_height = seriesParams.foot_height\n    pin_width = seriesParams.pin_width\n    pin_depth = seriesParams.pin_depth\n    pin_height = seriesParams.pin_height\n    pin_inside_distance = seriesParams.pin_inside_distance\n    pin_thickness = seriesParams.pin_thickness\n    chamfer_long = seriesParams.pin_chamfer_long\n    chamfer_short = seriesParams.pin_chamfer_short\n    sign = 1 if pin_1_side else -1\n    pin = cq.Workplane('YZ').workplane(offset=-pin_width - 2.0).moveTo(0, foot_height).line(sign * pin_thickness / 2, 0).line(sign * 1.27, -foot_height).line(0, -2.54).line(sign * -pin_thickness, 0).line(0, 2.54).line(sign * -1.27, foot_height).line(0, 1).close().extrude(pin_width).edges('|X').fillet(0.07)\n    return pin\n\ndef generate_2_pin_group(params, pin_1_side):\n    pin_pitch = params.pin_pitch\n    pin_y_pitch = params.pin_y_pitch\n    num_pins = params.num_pins\n    pin_a = generate_straight_pin(params, pin_1_side).translate((0, -pin_y_pitch / 2, 0))\n    pin_b = pin_a.translate((0, -2 * pin_y_pitch, 0))\n    pin_group = pin_a.union(pin_b)\n    return pin_group\n\ndef generate_pins(params):\n    pin_pitch = params.pin_pitch\n    num_pins = params.num_pins\n    pins = generate_2_pin_group(params, pin_1_side=True)\n    for i in range(1, num_pins // 2):\n        pins = pins.union(generate_2_pin_group(params, i % 2 == 0).translate((i * pin_pitch, 0, 0)))\n    return pins\n\ndef generate_2_contact_group(params):\n    pin_y_pitch = params.pin_y_pitch\n    foot_height = seriesParams.foot_height\n    pin_thickness = seriesParams.pin_thickness\n    pin_width = seriesParams.pin_width\n    y_offset = -(2 * pin_y_pitch)\n    c_list = [('start', {'position': (pin_y_pitch, foot_height), 'direction': 90.0, 'width': pin_thickness}), ('line', {'length': 4.5}), ('arc', {'radius': 0.2, 'angle': 35.0}), ('line', {'length': 3}), ('arc', {'radius': 2.0, 'angle': -70.0}), ('line', {'length': 2}), ('arc', {'radius': 0.2, 'angle': 35.0}), ('line', {'length': 2.8})]\n    ribbon = Ribbon(cq.Workplane('YZ').workplane(offset=-pin_width / 2.0), c_list)\n    contact1 = ribbon.drawRibbon().extrude(pin_width)\n    contact2 = contact1.mirror('XZ')\n    contact1 = contact1.union(contact2).translate((0, -3 * pin_y_pitch / 2.0, 0))\n    return contact1\n\ndef generate_contacts(params):\n    num_pins = params.num_pins\n    pin_pitch = params.pin_pitch\n    pair = generate_2_contact_group(params)\n    contacts = pair\n    for i in range(0, num_pins // 2):\n        contacts = contacts.union(pair.translate((i * pin_pitch, 0, 0)))\n    return contacts\n\ndef generate_body(params, calc_dim):\n    pin_inside_distance = seriesParams.pin_inside_distance\n    pin_width = seriesParams.pin_width\n    num_pins = params.num_pins\n    pin_pitch = params.pin_pitch\n    pin_y_pitch = params.pin_y_pitch\n    body_length = calc_dim.length\n    body_width = seriesParams.body_width\n    body_height = seriesParams.body_height\n    body_fillet_radius = seriesParams.body_fillet_radius\n    marker_x_inside = seriesParams.marker_x_inside\n    marker_y_inside = seriesParams.marker_y_inside\n    marker_size = seriesParams.marker_size\n    marker_depth = seriesParams.marker_depth\n    foot_height = seriesParams.foot_height\n    foot_width = seriesParams.foot_width\n    foot_length = seriesParams.foot_length\n    foot_inside_distance = seriesParams.foot_inside_distance\n    slot_length = calc_dim.slot_length\n    slot_outside_pin = seriesParams.slot_outside_pin\n    slot_width = seriesParams.slot_width\n    slot_depth = seriesParams.slot_depth\n    slot_chamfer = seriesParams.slot_chamfer\n    hole_width = seriesParams.hole_width\n    hole_length = seriesParams.hole_length\n    hole_offset = seriesParams.hole_offset\n    hole_depth = seriesParams.hole_depth\n    top_void_depth = seriesParams.top_void_depth\n    top_void_width = seriesParams.top_void_width\n    bottom_void_width = calc_dim.bottom_void_width\n    recess_depth = seriesParams.recess_depth\n    recess_large_width = seriesParams.recess_large_width\n    recess_small_width = seriesParams.recess_small_width\n    recess_height = seriesParams.recess_height\n    x_offset = (num_pins // 2 - 1) * pin_pitch / 2.0\n    y_offset = -(1.5 * pin_y_pitch)\n    body = cq.Workplane('XY').workplane(offset=foot_height).moveTo(x_offset, y_offset).rect(body_length, body_width).extrude(body_height).edges('|Z').fillet(body_fillet_radius).edges('>Z').fillet(body_fillet_radius)\n    body = body.faces('>Z').workplane().moveTo(-(body_length / 2) + marker_x_inside, body_width / 2 - marker_y_inside).line(-marker_size, -marker_size / 2).line(0, marker_size).close().cutBlind(-marker_depth)\n    foot = cq.Workplane('YZ').workplane(offset=body_length / 2 - foot_inside_distance).moveTo(y_offset - foot_length / 2, 0).line(foot_length * 0.2, 0).line(0, foot_height / 2).line(foot_length * 0.6, 0).line(0, -foot_height / 2).line(foot_length * 0.2, 0).line(0, foot_height).line(-foot_length, 0).close().extrude(-foot_width)\n    foot_mirror = foot.mirror('YZ')\n    foot = foot.union(foot_mirror).translate((x_offset, 0, 0))\n    body = body.union(foot)\n    body = body.faces('>Z').workplane().rect(slot_length, slot_width).cutBlind(-slot_depth)\n    chamfer = cq.Workplane('XY').workplane(offset=foot_height + body_height).moveTo(x_offset, y_offset).rect(slot_length + 2 * slot_chamfer, slot_width + 2 * slot_chamfer).workplane(offset=-slot_chamfer).rect(slot_length, slot_width).loft(combine=True)\n    body = body.cut(chamfer)\n    body = body.faces('>Z').workplane().center(0, hole_offset).rarray(pin_pitch, 1, num_pins // 2, 1).rect(hole_width, hole_length).center(0, -2 * hole_offset).rarray(pin_pitch, 1, num_pins // 2, 1).rect(hole_width, hole_length).cutBlind(-2)\n    body = body.faces('>Z').workplane(offset=-hole_depth).rarray(pin_pitch, 1, num_pins // 2, 1).rect(hole_width, top_void_width).cutBlind(-(top_void_depth - hole_depth))\n    body = body.faces('>Z').workplane(offset=-top_void_depth).rarray(pin_pitch, 1, num_pins // 2, 1).rect(hole_width, bottom_void_width).cutBlind(-(body_height - top_void_depth))\n    body = body.faces('>Z').workplane().center(body_length / 2.0 - recess_depth / 2.0, 0).rect(recess_depth, recess_small_width).cutBlind(-recess_height)\n    recess = cq.Workplane('XY').workplane(offset=foot_height + body_height).center(x_offset - body_length / 2.0 + recess_depth / 2.0, y_offset).rect(recess_depth, recess_large_width).extrude(-recess_height).edges('>X').edges('|Z').fillet(0.3)\n    body = body.cut(recess)\n    return body\n\ndef generate_part(part_key):\n    params = all_params[part_key]\n    calc_dim = dimensions(params)\n    pins = generate_pins(params)\n    body = generate_body(params, calc_dim)\n    contacts = generate_contacts(params)\n    return (pins, body, contacts)\nif 'module' in __name__:\n    part_to_build = 'ucon_17809_02x10_1.27mm'\n    FreeCAD.Console.PrintMessage('Started from CadQuery: building ' + part_to_build + '\\n')\n    pins, body, contacts = generate_part(part_to_build)\n    show(pins)\n    show(body)\n    show(contacts)",
  "line_no": 27,
  "line_no_percent": "21%"
}